kind = "DojoModel"
class_hash = "0x220f1de2490d28df1e7a9cc9cb10bda51dbdd9522c324d429a0a6568e94f225"
original_class_hash = "0x220f1de2490d28df1e7a9cc9cb10bda51dbdd9522c324d429a0a6568e94f225"
abi = "manifests/dev/abis/base/models/dojo_examples_models_emote_message.json"
name = "dojo_examples::models::emote_message"

[[members]]
name = "identity"
type = "ContractAddress"
key = true

[[members]]
name = "emote"
type = "Emote"
key = false
